/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

/**
 *
 * @author lucas
 */
public class Aluno extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Aluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSEXO = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanelFORMULARIO = new javax.swing.JPanel();
        jLabelDATANASCIMENTO = new javax.swing.JLabel();
        jLabelNOME = new javax.swing.JLabel();
        jLabelTELEFONE = new javax.swing.JLabel();
        jLabelALTURA = new javax.swing.JLabel();
        jLabelPESO = new javax.swing.JLabel();
        jLabelIMC = new javax.swing.JLabel();
        jTextFieldNOME = new javax.swing.JTextField();
        jTextFieldIMC = new javax.swing.JTextField();
        jTextFieldDATANASCIMENTO = new javax.swing.JTextField();
        jTextFieldALTURA = new javax.swing.JTextField();
        jTextFieldPESO = new javax.swing.JTextField();
        jTextFieldCODIGO = new javax.swing.JTextField();
        jRadioButtonMASCULINO = new javax.swing.JRadioButton();
        jRadioButtonFEMININO = new javax.swing.JRadioButton();
        jLabelTELEFONE1 = new javax.swing.JLabel();
        jLabelDATACADASTRO = new javax.swing.JLabel();
        jLabelCODIGO = new javax.swing.JLabel();
        jTextFieldTELEFONE1 = new javax.swing.JTextField();
        jTextFieldDATACADASTRO = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLISTAGEM = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonCANCELAR = new javax.swing.JButton();
        jButtonALTERAR = new javax.swing.JButton();
        jButtonVOLTAR = new javax.swing.JButton();
        jButtonSALVAR = new javax.swing.JButton();
        jLabelbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanelFORMULARIO.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));

        jLabelDATANASCIMENTO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDATANASCIMENTO.setText("*Data de Nascimento:");

        jLabelNOME.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNOME.setText("*Nome Completo:");

        jLabelTELEFONE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTELEFONE.setText("*Telefone:");

        jLabelALTURA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelALTURA.setText("*Altura:");

        jLabelPESO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPESO.setText("*Peso:");

        jLabelIMC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelIMC.setText("*IMC:");

        jTextFieldIMC.setEnabled(false);

        jTextFieldDATANASCIMENTO.setToolTipText("//");

        jTextFieldALTURA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldALTURAActionPerformed(evt);
            }
        });

        jTextFieldCODIGO.setEnabled(false);

        buttonGroupSEXO.add(jRadioButtonMASCULINO);
        jRadioButtonMASCULINO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButtonMASCULINO.setText("Masculino");

        buttonGroupSEXO.add(jRadioButtonFEMININO);
        jRadioButtonFEMININO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButtonFEMININO.setText("Feminino");

        jLabelTELEFONE1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTELEFONE1.setText("*Sexo:");

        jLabelDATACADASTRO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDATACADASTRO.setText("*DATA CADASTRO:");

        jLabelCODIGO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCODIGO.setText("CÓDIGO:");

        jTextFieldDATACADASTRO.setEnabled(false);

        jTableLISTAGEM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableLISTAGEM);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/lupa2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFORMULARIOLayout = new javax.swing.GroupLayout(jPanelFORMULARIO);
        jPanelFORMULARIO.setLayout(jPanelFORMULARIOLayout);
        jPanelFORMULARIOLayout.setHorizontalGroup(
            jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFORMULARIOLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTELEFONE)
                    .addComponent(jLabelNOME)
                    .addComponent(jLabelTELEFONE1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFORMULARIOLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jRadioButtonMASCULINO)
                        .addGap(130, 130, 130)
                        .addComponent(jRadioButtonFEMININO)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelFORMULARIOLayout.createSequentialGroup()
                        .addGroup(jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNOME, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelFORMULARIOLayout.createSequentialGroup()
                                .addGap(313, 313, 313)
                                .addComponent(jLabelALTURA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldALTURA, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(jLabelPESO)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFORMULARIOLayout.createSequentialGroup()
                                .addComponent(jTextFieldPESO, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jLabelIMC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelFORMULARIOLayout.createSequentialGroup()
                                .addComponent(jLabelDATANASCIMENTO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldDATANASCIMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51))))
            .addGroup(jPanelFORMULARIOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFORMULARIOLayout.createSequentialGroup()
                        .addComponent(jLabelCODIGO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelDATACADASTRO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDATACADASTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFORMULARIOLayout.createSequentialGroup()
                    .addGap(208, 208, 208)
                    .addComponent(jTextFieldTELEFONE1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(864, Short.MAX_VALUE)))
        );
        jPanelFORMULARIOLayout.setVerticalGroup(
            jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFORMULARIOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCODIGO)
                    .addComponent(jTextFieldCODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDATACADASTRO)
                    .addComponent(jTextFieldDATACADASTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNOME, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNOME)
                        .addComponent(jLabelDATANASCIMENTO)
                        .addComponent(jTextFieldDATANASCIMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTELEFONE)
                    .addComponent(jLabelALTURA)
                    .addComponent(jTextFieldALTURA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPESO)
                    .addComponent(jTextFieldPESO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIMC)
                    .addComponent(jTextFieldIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMASCULINO)
                    .addComponent(jRadioButtonFEMININO)
                    .addComponent(jLabelTELEFONE1))
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFORMULARIOLayout.createSequentialGroup()
                    .addGap(147, 147, 147)
                    .addComponent(jTextFieldTELEFONE1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(399, Short.MAX_VALUE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));

        jButtonCANCELAR.setText("CANCELAR");

        jButtonALTERAR.setText("ALTERAR");

        jButtonVOLTAR.setText("VOLTAR");
        jButtonVOLTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVOLTARActionPerformed(evt);
            }
        });

        jButtonSALVAR.setText("SALVAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVOLTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSALVAR, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(jButtonALTERAR, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addComponent(jButtonCANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCANCELAR, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jButtonALTERAR, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jButtonVOLTAR, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jButtonSALVAR, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelFORMULARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelFORMULARIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 20, 1200, 680);

        jLabelbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/pilates_1.jpg"))); // NOI18N
        getContentPane().add(jLabelbackground);
        jLabelbackground.setBounds(0, 4, 1280, 720);

        setSize(new java.awt.Dimension(1296, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldALTURAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldALTURAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldALTURAActionPerformed

    private void jButtonVOLTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVOLTARActionPerformed
        // TODO add your handling code here:
        Menu menu1 = new Menu();
        menu1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVOLTARActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSEXO;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonALTERAR;
    private javax.swing.JButton jButtonCANCELAR;
    private javax.swing.JButton jButtonSALVAR;
    private javax.swing.JButton jButtonVOLTAR;
    private javax.swing.JLabel jLabelALTURA;
    private javax.swing.JLabel jLabelCODIGO;
    private javax.swing.JLabel jLabelDATACADASTRO;
    private javax.swing.JLabel jLabelDATANASCIMENTO;
    private javax.swing.JLabel jLabelIMC;
    private javax.swing.JLabel jLabelNOME;
    private javax.swing.JLabel jLabelPESO;
    private javax.swing.JLabel jLabelTELEFONE;
    private javax.swing.JLabel jLabelTELEFONE1;
    private javax.swing.JLabel jLabelbackground;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelFORMULARIO;
    private javax.swing.JRadioButton jRadioButtonFEMININO;
    private javax.swing.JRadioButton jRadioButtonMASCULINO;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLISTAGEM;
    private javax.swing.JTextField jTextFieldALTURA;
    private javax.swing.JTextField jTextFieldCODIGO;
    private javax.swing.JTextField jTextFieldDATACADASTRO;
    private javax.swing.JTextField jTextFieldDATANASCIMENTO;
    private javax.swing.JTextField jTextFieldIMC;
    private javax.swing.JTextField jTextFieldNOME;
    private javax.swing.JTextField jTextFieldPESO;
    private javax.swing.JTextField jTextFieldTELEFONE1;
    // End of variables declaration//GEN-END:variables
}
