/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author lucas
 */
public class TurmaView extends javax.swing.JFrame {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form NewJFrame
     */
    public TurmaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelFORMULARIO = new javax.swing.JPanel();
        jLabelDATANAINICIAL = new javax.swing.JLabel();
        jLabelPROFESSOR = new javax.swing.JLabel();
        jLabelTURMA = new javax.swing.JLabel();
        jLabelDATAFINAL = new javax.swing.JLabel();
        jTextFieldDATAINICIAL = new javax.swing.JTextField();
        jTextFieldDATAFINAL = new javax.swing.JTextField();
        jTextFieldDURACAO = new javax.swing.JTextField();
        jLabelHORARIOAULA = new javax.swing.JLabel();
        jLabelDURACAO = new javax.swing.JLabel();
        jComboBoxHORARIOAULA = new javax.swing.JComboBox<>();
        jTextFieldTURMA = new javax.swing.JTextField();
        jComboBoxPROFESSOR = new javax.swing.JComboBox<>();
        jScrollPaneLISTAGEM = new javax.swing.JScrollPane();
        jTableLISTAGEM = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonCANCELAR = new javax.swing.JButton();
        jButtonALTERAR = new javax.swing.JButton();
        jButtonVOLTAR = new javax.swing.JButton();
        jButtonSALVAR = new javax.swing.JButton();
        jLabelbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanelFORMULARIO.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));

        jLabelDATANAINICIAL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDATANAINICIAL.setText("Data Inicial:");

        jLabelPROFESSOR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPROFESSOR.setText("*Professor:");

        jLabelTURMA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTURMA.setText("*Turma:");

        jLabelDATAFINAL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDATAFINAL.setText("Data Final:");

        jTextFieldDATAINICIAL.setToolTipText("//");

        jTextFieldDURACAO.setOpaque(false);

        jLabelHORARIOAULA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelHORARIOAULA.setText("Horário de Aula:");

        jLabelDURACAO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDURACAO.setText("Duração:");

        jComboBoxHORARIOAULA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30 minutos", "60 minutos", "90 minutos", "120 minutos" }));

        jTextFieldTURMA.setToolTipText("//");

        jComboBoxPROFESSOR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTableLISTAGEM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneLISTAGEM.setViewportView(jTableLISTAGEM);

        javax.swing.GroupLayout jPanelFORMULARIOLayout = new javax.swing.GroupLayout(jPanelFORMULARIO);
        jPanelFORMULARIO.setLayout(jPanelFORMULARIOLayout);
        jPanelFORMULARIOLayout.setHorizontalGroup(
            jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFORMULARIOLayout.createSequentialGroup()
                .addGroup(jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFORMULARIOLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelDURACAO)
                            .addComponent(jLabelTURMA)
                            .addComponent(jLabelPROFESSOR)
                            .addComponent(jLabelHORARIOAULA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxHORARIOAULA, 0, 214, Short.MAX_VALUE)
                            .addComponent(jComboBoxPROFESSOR, 0, 214, Short.MAX_VALUE)
                            .addComponent(jTextFieldTURMA)
                            .addComponent(jTextFieldDURACAO))
                        .addGap(43, 43, 43)
                        .addGroup(jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelDATAFINAL)
                            .addComponent(jLabelDATANAINICIAL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldDATAINICIAL, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(jTextFieldDATAFINAL)))
                    .addGroup(jPanelFORMULARIOLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneLISTAGEM, javax.swing.GroupLayout.PREFERRED_SIZE, 1176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFORMULARIOLayout.setVerticalGroup(
            jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFORMULARIOLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPROFESSOR)
                    .addComponent(jLabelDATANAINICIAL)
                    .addComponent(jTextFieldDATAINICIAL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPROFESSOR, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTURMA)
                    .addComponent(jLabelDATAFINAL)
                    .addComponent(jTextFieldDATAFINAL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTURMA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHORARIOAULA)
                    .addComponent(jComboBoxHORARIOAULA, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanelFORMULARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDURACAO)
                    .addComponent(jTextFieldDURACAO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jScrollPaneLISTAGEM, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));

        jButtonCANCELAR.setText("CANCELAR");

        jButtonALTERAR.setText("ALTERAR");

        jButtonVOLTAR.setText("VOLTAR");
        jButtonVOLTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVOLTARActionPerformed(evt);
            }
        });

        jButtonSALVAR.setText("SALVAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVOLTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSALVAR, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(jButtonALTERAR, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addComponent(jButtonCANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCANCELAR, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jButtonALTERAR, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jButtonVOLTAR, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jButtonSALVAR, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelFORMULARIO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelFORMULARIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 20, 1200, 680);

        jLabelbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/pilates_1.jpg"))); // NOI18N
        getContentPane().add(jLabelbackground);
        jLabelbackground.setBounds(0, 0, 1280, 720);

        setSize(new java.awt.Dimension(1296, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVOLTARActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonVOLTARActionPerformed
        // TODO add your handling code here:
        Menu menu1 = new Menu();
        menu1.setVisible(true);
        dispose();
    }// GEN-LAST:event_jButtonVOLTARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TurmaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TurmaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TurmaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TurmaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TurmaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonALTERAR;
    private javax.swing.JButton jButtonCANCELAR;
    private javax.swing.JButton jButtonSALVAR;
    private javax.swing.JButton jButtonVOLTAR;
    private javax.swing.JComboBox<String> jComboBoxHORARIOAULA;
    private javax.swing.JComboBox<String> jComboBoxPROFESSOR;
    private javax.swing.JLabel jLabelDATAFINAL;
    private javax.swing.JLabel jLabelDATANAINICIAL;
    private javax.swing.JLabel jLabelDURACAO;
    private javax.swing.JLabel jLabelHORARIOAULA;
    private javax.swing.JLabel jLabelPROFESSOR;
    private javax.swing.JLabel jLabelTURMA;
    private javax.swing.JLabel jLabelbackground;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelFORMULARIO;
    private javax.swing.JScrollPane jScrollPaneLISTAGEM;
    private javax.swing.JTable jTableLISTAGEM;
    private javax.swing.JTextField jTextFieldDATAFINAL;
    private javax.swing.JTextField jTextFieldDATAINICIAL;
    private javax.swing.JTextField jTextFieldDURACAO;
    private javax.swing.JTextField jTextFieldTURMA;
    // End of variables declaration//GEN-END:variables
}
